// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgpucwwhubbbuxcqsalx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncHVjd3dodWJiYnV4Y3FzYWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDU1MDMsImV4cCI6MjA2NTAyMTUwM30.hgv9HEb5LW8xZJgodkdr35koTN58H_u8O4heroRySmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);